import test from 'node:test';import assert from 'node:assert/strict';
import {createPaceBackup} from '../src/backup.js';
import {validatePaceBackup,paceStorageSnapshot,importPaceBackup} from '../src/backup-import.js';
import {emptyStudy,lectureItems,loadStudy,STUDY_KEY} from '../src/study.js';
import {loadCertifications} from '../src/certifications.js';
import {loadScopedAvailability,emptyAvailability} from '../src/availability.js';
import {loadDistributionSettings} from '../src/distribution-settings.js';
import {calculateDistribution} from '../src/distribution-preview.js';import {planningMinutes,loadPlanning} from '../src/study-planning.js';
function store(entries=[]){const map=new Map(entries);return {map,get length(){return map.size;},key:i=>[...map.keys()][i],getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,String(value)),removeItem:key=>map.delete(key)};}
const source=()=>store([['pace.certifications.v1',JSON.stringify([{id:'p',name:'테스트 자격증',color:'#F06B85',examDate:'2040-02-10'}])],[STUDY_KEY,JSON.stringify({...emptyStudy(),catalog:[{id:'a',planId:'p',category:'교재',studyKind:'book',title:'가상 항목',expectedMinutes:60,date:'2040-02-03'},{id:'b',planId:'p',category:'교재',studyKind:'book',title:'완료 항목',date:'2040-02-01'},{id:'c',planId:'p',category:'연습',studyKind:'book',title:'개수 항목'}],lectureCompletion:{b:{completed:true,updatedAt:'2040-02-01T00:00:00Z'}},itemOverrides:{a:{date:'2040-02-04',scheduleSource:'automatic'}}})],['pace.availability.v2',JSON.stringify({version:2,certifications:{p:{...emptyAvailability(),daily:180,startDate:'2040-02-01',endDate:null}}})],['pace.planning-settings.v1',JSON.stringify({version:1,certifications:{p:{speed:1.5}}})],['pace.distribution-settings.v1',JSON.stringify({version:1,certifications:{p:{priority:[{category:'교재',itemIds:['a','b']},{category:'연습',itemIds:['c']}],mode:'parallel',countBased:{enabled:true,dailyLimit:null},examPrep:[{itemId:'a',daysBefore:1}]}}})],['pace.personal-events.v1',JSON.stringify([{id:'event',title:'가상 일정',date:'2040-02-06'}])]]);
const prepare=()=>validatePaceBackup(JSON.stringify(createPaceBackup(source())));
test('preview validation is read only and reports certificates, completion, dates and settings',()=>{const original=source(),before=paceStorageSnapshot(original),prepared=validatePaceBackup(JSON.stringify(createPaceBackup(original)));assert.equal(paceStorageSnapshot(original),before);assert.equal(prepared.items,3);assert.equal(prepared.completed,1);assert.equal(prepared.scheduled,2);assert.equal(prepared.personal,1);assert.equal(prepared.certifications[0].name,'테스트 자격증');});
test('fresh browser storage restores all raw data, dates, completion and distribution behavior',()=>{const original=source(),fresh=store([['another-app','keep']]),prepared=prepare();importPaceBackup(fresh,prepared,{expectedSnapshot:paceStorageSnapshot(fresh),confirmed:true});assert.equal(paceStorageSnapshot(fresh),paceStorageSnapshot(original));assert.equal(fresh.getItem('another-app'),'keep');assert.deepEqual(lectureItems(loadStudy(fresh)),lectureItems(loadStudy(original)));assert.equal(loadCertifications(fresh,[])[0].name,'테스트 자격증');assert.equal(loadPlanning(fresh).certifications.p.speed,1.5);assert.equal(loadDistributionSettings(fresh).certifications.p.mode,'parallel');const calc=storage=>calculateDistribution({data:loadStudy(storage),plan:loadCertifications(storage,[])[0],availability:loadScopedAvailability(storage),priority:['교재','연습'],today:new Date(2040,1,2),mode:'parallel',countSettings:{enabled:true,dailyLimit:null},examPrep:[{itemId:'a',daysBefore:1}],minutesFor:planningMinutes,speed:1.5});assert.deepEqual(calc(fresh),calc(original));});
test('existing data requires explicit confirmation and rejects concurrent changes',()=>{const target=source(),before=paceStorageSnapshot(target),prepared=prepare();assert.throws(()=>importPaceBackup(target,prepared,{expectedSnapshot:before}),/확인/);assert.equal(paceStorageSnapshot(target),before);target.setItem('pace.changed','{}');assert.throws(()=>importPaceBackup(target,prepared,{expectedSnapshot:before,confirmed:true}),/변경/);});
test('confirmed restore is idempotent and replaces only PACE namespace',()=>{const target=source();target.setItem('pace.extra','{}');target.setItem('another-app','keep');const prepared=prepare();for(let i=0;i<2;i++)importPaceBackup(target,prepared,{expectedSnapshot:paceStorageSnapshot(target),confirmed:true});assert.equal(target.getItem('pace.extra'),null);assert.equal(target.getItem('another-app'),'keep');assert.equal(lectureItems(loadStudy(target)).length,3);});
test('malformed, unsupported, foreign, invalid links, duplicates and mismatched projections rejected',()=>{assert.throws(()=>validatePaceBackup('bad'));assert.throws(()=>validatePaceBackup('{}'));for(const change of [b=>b.version=2,b=>b.rawStorage['foreign']='{}',b=>b.resolvedStudyItems[0].completed=true,b=>{const data=JSON.parse(b.rawStorage[STUDY_KEY]);data.catalog[0].planId='missing';b.rawStorage[STUDY_KEY]=JSON.stringify(data);},b=>{const data=JSON.parse(b.rawStorage[STUDY_KEY]);data.catalog[1].id='a';b.rawStorage[STUDY_KEY]=JSON.stringify(data);},b=>{const data=JSON.parse(b.rawStorage[STUDY_KEY]);data.catalog[0].date='2040-02-31';b.rawStorage[STUDY_KEY]=JSON.stringify(data);},b=>b.rawStorage['pace.planning-settings.v1']='broken']){const backup=createPaceBackup(source());change(backup);assert.throws(()=>validatePaceBackup(JSON.stringify(backup)));}});
test('mid-write storage failure restores exact previous state',()=>{const target=store([['pace.previous','{}'],['another-app','keep']]),before=paceStorageSnapshot(target),write=target.setItem;let fail=true;target.setItem=(key,value)=>{if(key==='pace.study-plans.v1'&&fail){fail=false;throw Error('quota');}write(key,value);};assert.throws(()=>importPaceBackup(target,prepare(),{expectedSnapshot:before,confirmed:true}),/되돌렸/);assert.equal(paceStorageSnapshot(target),before);assert.equal(target.getItem('another-app'),'keep');});
