import test from 'node:test';import assert from 'node:assert/strict';
import {orderedCertificationChoices,defaultCertificationId} from '../src/certifications.js';
const plans=[{id:'practical',name:'정보처리기사 실기',examDate:'2026-10-25'},{id:'sqld',name:'SQLD',examDate:'2026-11-14'},{id:'history',name:'한국사능력검정시험',examDate:'2026-11-28'}];
test('예정 시험은 빠른 날짜순, 시험 당일 포함하고 지난 시험은 뒤로 표시',()=>{assert.deepEqual(orderedCertificationChoices([...plans].reverse(),new Date(2026,9,10)).map(plan=>plan.id),['practical','sqld','history']);assert.equal(defaultCertificationId(plans,null,new Date(2026,9,25)),'practical');assert.equal(defaultCertificationId(plans,null,new Date(2026,9,26)),'sqld');assert.deepEqual(orderedCertificationChoices(plans,new Date(2026,9,26)).map(plan=>plan.id),['sqld','history','practical']);assert.equal(defaultCertificationId(plans,null,new Date(2026,10,15)),'history');});
test('수동 선택은 시험일이 지나거나 다른 시험이 가까워져도 유지',()=>{assert.equal(defaultCertificationId(plans,'practical',new Date(2026,10,15)),'practical');assert.equal(defaultCertificationId(plans,'history',new Date(2026,9,10)),'history');assert.equal(defaultCertificationId(plans,'deleted',new Date(2026,9,26)),'sqld');});
test('미정 날짜·동일 날짜·모두 지난 시험·빈 목록을 안정적으로 처리하고 원본 보존',()=>{const data=[{id:'past',examDate:'2026-01-01',completed:false},{id:'unset',examDate:null},{id:'a',examDate:'2026-11-14'},{id:'b',examDate:'2026-11-14'}],before=structuredClone(data);assert.deepEqual(orderedCertificationChoices(data,new Date(2026,9,10)).map(plan=>plan.id),['a','b','unset','past']);assert.deepEqual(data,before);assert.equal(data[0].completed,false);assert.equal(defaultCertificationId([],null,new Date(2026,9,10)),'');assert.equal(defaultCertificationId(plans,null,new Date(2026,11,1)),'practical');});

import {certificationChoiceEntries} from '../src/certifications.js';
test('지난 시험 구분선은 지난 시험 앞에 한 번 표시, 미래 시험만 있으면 없음',()=>{assert.ok(!certificationChoiceEntries(plans,new Date(2026,9,10)).some(entry=>entry.separator));const entries=certificationChoiceEntries(plans,new Date(2026,10,15));assert.deepEqual(entries.map(entry=>entry.separator?'divider':entry.plan.id),['history','divider','practical','sqld']);assert.equal(entries.filter(entry=>entry.separator).length,1);assert.equal(certificationChoiceEntries(plans,new Date(2026,11,1))[0].separator,true);assert.deepEqual(certificationChoiceEntries([],new Date(2026,11,1)),[]);});
