import test from 'node:test';import assert from 'node:assert/strict';
import {calculateDistribution} from '../src/distribution-preview.js';import {planningMinutes} from '../src/study-planning.js';import {emptyStudy} from '../src/study.js';import {emptyAvailability} from '../src/availability.js';import {configureMilestone} from '../src/certifications.js';
const today=new Date(2026,9,10),plan={id:'p',examDate:'2026-10-20',goals:[]};
const item=(category,index,minutes)=>({id:category+index,planId:'p',category,title:category+' '+index,order:index,studyKind:'book',...(minutes==null?{}:{expectedMinutes:minutes}),date:'2026-10-15'});
const study=catalog=>({...emptyStudy(),catalog});const rules=extra=>({version:2,certifications:{p:{...emptyAvailability(),daily:240,startDate:'2026-10-01',endDate:null,...extra}}});
const calc=(data,extra={})=>calculateDistribution({data,plan,availability:rules(),priority:['1과목','2과목','기출문제','모의고사'],today,speed:1,minutesFor:planningMinutes,...extra});
const sqld=()=>study([['1과목',11],['2과목',20],['기출문제',17],['모의고사',11]].flatMap(([category,count])=>Array.from({length:count},(_,i)=>item(category,i+1))));
test('SQLD 59개를 순차 개수 기준으로 학습일에 균등하게 배치하고 순서·원본·시간 미설정 유지',()=>{const data=sqld(),before=JSON.stringify(data),result=calc(data);assert.equal(result.assignments.length,59);assert.equal(result.summary.countAssigned,59);assert.equal(result.summary.assignedMinutes,0);assert.equal(result.missing.length,0);assert.equal(result.unplaced.length,0);assert.equal(new Set(result.assignments.map(item=>item.itemId)).size,59);assert.ok(result.assignments.every(item=>item.minutes===null&&item.basis==='count'));assert.ok(result.days.every(day=>day.items.length>=5&&day.items.length<=6));assert.deepEqual(result.assignments.map(entry=>entry.itemId),data.catalog.map(item=>item.id));assert.equal(JSON.stringify(data),before);});
test('31개를 10일에 3~4개로 배치하고 자동 한도를 무제한 0분 처리하지 않음',()=>{const result=calc(study(Array.from({length:31},(_,i)=>item('1과목',i+1))));assert.equal(result.assignments.length,31);assert.equal(result.days.length,10);assert.ok(result.days.every(day=>day.items.length===3||day.items.length===4));});
test('병행 SQLD 분류 두 개를 함께 진행하고 하루 두 분류 이하·분류 내부 순서 유지',()=>{const data=sqld(),result=calc(data,{mode:'parallel'});assert.equal(result.assignments.length,59);assert.equal(new Set(result.days[0].items.map(entry=>data.catalog.find(item=>item.id===entry.itemId).category)).size,2);for(const day of result.days)assert.ok(new Set(day.items.map(entry=>data.catalog.find(item=>item.id===entry.itemId).category)).size<=2);for(const category of ['1과목','2과목','기출문제','모의고사'])assert.deepEqual(result.assignments.filter(entry=>entry.itemId.startsWith(category)).map(entry=>entry.itemId),data.catalog.filter(item=>item.category===category).map(item=>item.id));});
test('휴식·0분·예외·완료 기록을 보존하고 공부 가능한 날짜만 사용',()=>{const data=sqld();data.lectureCompletion={'1과목1':{completed:true}};const result=calc(data,{availability:rules({restDays:[6],exceptions:{'2026-10-11':{kind:'study',minutes:0},'2026-10-12':{kind:'rest',minutes:0}}})});assert.equal(result.assignments.length,58);assert.ok(!result.assignments.some(entry=>entry.itemId==='1과목1'));assert.ok(result.days.every(day=>day.date!=='2026-10-10'&&day.date!=='2026-10-17'&&day.date!=='2026-10-11'&&day.date!=='2026-10-12'));});
test('수동 한도 2개는 지키고 미배치 사유와 항목은 중복하지 않음',()=>{const result=calc(sqld(),{countSettings:{enabled:true,dailyLimit:2}});assert.equal(result.assignments.length,20);assert.equal(result.missing.length,39);assert.ok(result.missing.every(item=>item.reason.includes('한도')));assert.ok(result.days.every(day=>day.items.length<=2));assert.equal(new Set([...result.assignments,...result.missing,...result.unplaced].map(item=>item.itemId)).size,59);});
test('시간·개수 혼합 분류 순서 유지, 실제 시간만 합산하고 한도와 시간 제한 독립',()=>{const data=study([item('1과목',1,120),item('1과목',2),item('1과목',3,120),item('1과목',4),item('2과목',1,60)]),result=calc(data,{countSettings:{enabled:true,dailyLimit:1}});assert.equal(result.assignments.length,5);assert.equal(result.summary.assignedMinutes,300);assert.equal(result.summary.countAssigned,2);assert.ok(result.days.every(day=>day.used<=day.capacity&&day.items.filter(item=>item.basis==='count').length<=1));assert.deepEqual(result.assignments.filter(entry=>entry.itemId.startsWith('1과목')).map(entry=>entry.itemId),['1과목1','1과목2','1과목3','1과목4']);});
test('시간 없는 시험 직전 지정 항목은 지정일 먼저 배치하고 병행 분류 제한·휴식 실패 유지',()=>{const data=sqld(),examPrep=[{itemId:'기출문제1',daysBefore:1},{itemId:'기출문제2',daysBefore:1}];for(const mode of ['sequential','parallel']){const result=calc(data,{mode,examPrep});const last=result.days.find(day=>day.date==='2026-10-19');assert.deepEqual(last.items.slice(0,2).map(item=>item.itemId),['기출문제1','기출문제2']);assert.equal(result.assignments.filter(item=>item.itemId==='기출문제1').length,1);if(mode==='parallel')assert.ok(new Set(last.items.map(entry=>data.catalog.find(item=>item.id===entry.itemId).category)).size<=2);}const blocked=calc(data,{examPrep,availability:rules({exceptions:{'2026-10-19':{kind:'rest',minutes:0}}})});assert.equal(blocked.unplaced.filter(item=>item.type==='exam-prep').length,2);assert.ok(blocked.missing.every(item=>!examPrep.some(ref=>ref.itemId===item.itemId)));});
test('개수 기반 이정표를 고려하여 목표일까지 배치하고 늦거나 미배치면 실제 결과 판정',()=>{const data=study(Array.from({length:12},(_,i)=>item('1과목',i+1))),goal=configureMilestone({id:'g',title:'1과목 완료',date:'2026-10-12'},data,'p',true,['1과목']);const result=calc(data,{plan:{...plan,goals:[goal]}});assert.equal(result.milestones[0].status,'met');assert.equal(result.milestones[0].onTime,12);const limited=calc(data,{plan:{...plan,goals:[goal]},countSettings:{enabled:true,dailyLimit:1}});assert.equal(limited.milestones[0].status,'impossible');});
test('시간 기반만 있는 순차·병행은 개수 설정 유무와 관계없이 동일',()=>{const data=study([item('1과목',1,120),item('1과목',2,120),item('2과목',1,60)]);for(const mode of ['sequential','parallel'])assert.deepEqual(calc(data,{mode}),calc(data,{mode,countSettings:{enabled:false,dailyLimit:1}}));});
test('개수 분배 해제·학습일 없음·지난 시험일은 임의 배치하지 않음',()=>{const data=sqld();assert.equal(calc(data,{countSettings:{enabled:false,dailyLimit:null}}).missing.length,59);assert.equal(calc(data,{availability:rules({daily:0})}).assignments.length,0);assert.equal(calc(data,{plan:{...plan,examDate:'2026-10-10'}}).assignments.length,0);});

test('사용자 지정 우선순위와 여러 유형에 공통 적용하고 다른 자격증 및 원본을 변경하지 않음',()=>{const data=sqld();data.catalog.forEach((item,index)=>item.studyKind=['book','past','mock','review','other'][index%5]);data.catalog.push({...item('다른 자격증',1),planId:'q'});const snapshot=JSON.stringify(data);Object.freeze(data);Object.freeze(data.catalog);data.catalog.forEach(Object.freeze);const result=calc(data,{priority:['모의고사','기출문제','2과목','1과목']});assert.equal(result.assignments.length,59);assert.ok(result.assignments[0].itemId.startsWith('모의고사'));assert.ok(result.assignments.every(entry=>!entry.itemId.startsWith('다른 자격증')));assert.equal(JSON.stringify(data),snapshot);});

test('SQLD 31개 교재·17시간 기출·11개 모의고사는 별도 한도로 같은 날 배치, 불필요한 미배치 없음',()=>{const data=sqld();for(const item of data.catalog)if(item.category==='기출문제')item.expectedMinutes=60;const before=JSON.stringify(data);for(const mode of ['sequential','parallel']){const result=calc(data,{mode,today:new Date(2026,9,26),plan:{...plan,examDate:'2026-11-13'},availability:rules({restDays:[0,5]})});assert.equal(result.summary.assignedMinutes,1020);assert.equal(result.summary.countAssigned,42);assert.equal(result.assignments.length,59);assert.equal(result.missing.length+result.unplaced.length,0);assert.ok(result.days.some(day=>day.items.some(item=>item.basis==='count')&&day.items.some(item=>item.minutes!=null)));assert.ok(result.days.every(day=>day.used<=day.capacity));if(mode==='parallel')for(const day of result.days)assert.ok(new Set(day.items.map(entry=>data.catalog.find(item=>item.id===entry.itemId).category)).size<=2);}assert.equal(JSON.stringify(data),before);});

test('혼합 데이터의 실제 시간 부족과 하루 항목 길이 제약을 구분하고 순차 우선순위로 뒤쪽 모의고사는 대기',()=>{const data=sqld();for(const item of data.catalog)if(item.category==='기출문제')item.expectedMinutes=60;const shortage=calc(data,{plan:{...plan,examDate:'2026-10-12'},availability:rules({daily:60})});assert.equal(shortage.summary.assignedMinutes,120);assert.equal(shortage.summary.countAssigned,31);assert.equal(shortage.missing.length,11);assert.equal(shortage.unplaced.length,15);assert.ok(shortage.unplaced.every(item=>item.reason.includes('시간 기반 학습 가능 시간이 부족')));const tooLong=calc(data,{availability:rules({daily:30})});assert.equal(tooLong.summary.assignedMinutes,0);assert.equal(tooLong.summary.countAssigned,31);assert.equal(tooLong.missing.length,11);assert.equal(tooLong.unplaced.length,17);assert.ok(tooLong.unplaced.every(item=>item.reason.includes('분할 없이')));});

test('혼합 순차는 전체 분류 우선순위 엄수: 앞 분류 마지막 항목보다 다음 분류 첫 항목이 앞서지 않음',()=>{const data=sqld();for(const item of data.catalog)if(item.category==='기출문제')item.expectedMinutes=60;const result=calc(data,{today:new Date(2026,9,26),plan:{...plan,examDate:'2026-11-13'},availability:rules({restDays:[0,5]})});assert.deepEqual(result.assignments.map(entry=>entry.itemId),data.catalog.map(item=>item.id));const ranks=['1과목','2과목','기출문제','모의고사'];let previous=-1;for(const assignment of result.assignments){const category=data.catalog.find(item=>item.id===assignment.itemId).category,rank=ranks.indexOf(category);assert.ok(rank>=previous);previous=rank;}assert.equal(result.summary.assignedMinutes,1020);assert.equal(result.summary.countAssigned,42);assert.equal(result.missing.length+result.unplaced.length,0);});
test('사용자가 고정한 작은 개수 한도로 앞 분류가 남으면 뒤쪽 시간 항목을 먼저 진행하지 않음',()=>{const data=study([item('1과목',1),item('1과목',2),item('2과목',1,60),item('모의고사',1)]),result=calc(data,{countSettings:{enabled:true,dailyLimit:1}});assert.equal(result.assignments.find(entry=>entry.itemId==='1과목1').date,'2026-10-10');assert.equal(result.assignments.find(entry=>entry.itemId==='1과목2').date,'2026-10-11');assert.equal(result.assignments.find(entry=>entry.itemId==='2과목1').date,'2026-10-11');assert.equal(result.assignments.find(entry=>entry.itemId==='모의고사1').date,'2026-10-12');});
