import test from 'node:test';import assert from 'node:assert/strict';
import {DISTRIBUTION_KEY,loadDistributionSettings,distributionPriority,saveDistributionPriority} from '../src/distribution-settings.js';
import {emptyStudy} from '../src/study.js';import {updateStudyCategory} from '../src/study-item-edit.js';
const data=()=>({...emptyStudy(),catalog:['모의고사','SQL','특강','이론','기출문제','프로그래밍언어'].map((category,i)=>({id:'p'+i,planId:'p',category,studyKind:'mock',date:'2026-10-12',expectedMinutes:60})).concat([{id:'q1',planId:'q',category:'B'},{id:'q2',planId:'q',category:'A'}]),lectureCompletion:{p0:{completed:true}},categoryColors:{p:{이론:'#aa66cc'}},categoryOrder:{p:['모의고사','SQL','특강','이론','기출문제','프로그래밍언어']}});
function storage(){const entries=new Map([['pace.study-plans.v1','original'],['pace.certifications.v1','goals']]);return {entries,getItem:key=>entries.get(key)??null,setItem:(key,value)=>entries.set(key,value)};}
test('모든 자격증의 초기 우선순위는 등록된 학습 분류 표시 순서를 사용',()=>{
 const settings=loadDistributionSettings(storage()),study=data();assert.deepEqual(distributionPriority(study,{id:'p',name:'정보처리기사 실기'},settings),['모의고사','SQL','특강','이론','기출문제','프로그래밍언어']);assert.deepEqual(distributionPriority(study,{id:'q',name:'다른 자격증'},settings),['B','A']);
});
test('사용자 우선순위 독립 저장·복원과 학습 항목 표시 순서 및 기존 데이터 보존',()=>{
 const store=storage(),study=data(),snapshot=structuredClone(study);const order=['SQL','이론','모의고사','기출문제','특강','프로그래밍언어'];saveDistributionPriority(store,study,'p',order);saveDistributionPriority(store,study,'q',['A','B']);const loaded=loadDistributionSettings(store);assert.deepEqual(distributionPriority(study,{id:'p',name:'정보처리기사 실기'},loaded),order);assert.deepEqual(distributionPriority(study,{id:'q',name:'다른 자격증'},loaded),['A','B']);assert.equal(store.getItem('pace.study-plans.v1'),'original');assert.equal(store.getItem('pace.certifications.v1'),'goals');assert.deepEqual(study,snapshot);
});
test('분류명 변경 후 우선순위 유지, 새 분류는 마지막에 추가하고 삭제 분류는 제외',()=>{
 const store=storage(),study=data();saveDistributionPriority(store,study,'p',['SQL','이론','모의고사','기출문제','특강','프로그래밍언어']);const renamed=updateStudyCategory(study,'p','이론',{name:'핵심 이론'});renamed.catalog.push({id:'new',planId:'p',category:'복습'});renamed.catalog=renamed.catalog.filter(item=>item.category!=='특강');assert.deepEqual(distributionPriority(renamed,{id:'p',name:'정보처리기사 실기'},loadDistributionSettings(store)),['SQL','핵심 이론','모의고사','기출문제','프로그래밍언어','복습']);
});
test('미저장 우선순위는 복원 값에 영향이 없고 손상 설정과 잘못된 분류 저장을 차단',()=>{
 const store=storage(),study=data(),plan={id:'p',name:'정보처리기사 실기'};const order=distributionPriority(study,plan,loadDistributionSettings(store));order.reverse();assert.equal(store.getItem(DISTRIBUTION_KEY),null);assert.equal(distributionPriority(study,plan,loadDistributionSettings(store))[0],'모의고사');assert.throws(()=>saveDistributionPriority(store,study,'p',['SQL']));store.setItem(DISTRIBUTION_KEY,'{broken');assert.throws(()=>saveDistributionPriority(store,study,'p',order));assert.equal(store.getItem(DISTRIBUTION_KEY),'{broken');
});

import {distributionMode,previewForDistributionMode} from '../src/distribution-settings.js';
test('분배 방식 기본값은 순차 학습, 병행 선택 저장·복원은 자격증별 독립적이며 우선순위 보존',()=>{
 const store=storage(),study=data(),order=['SQL','이론','모의고사','기출문제','특강','프로그래밍언어'],snapshot=structuredClone(study);assert.equal(distributionMode(loadDistributionSettings(store),'p'),'sequential');saveDistributionPriority(store,study,'p',order);assert.equal(distributionMode(loadDistributionSettings(store),'p'),'sequential');saveDistributionPriority(store,study,'p',order,'parallel');saveDistributionPriority(store,study,'q',['B','A'],'sequential');const settings=loadDistributionSettings(store);assert.equal(distributionMode(settings,'p'),'parallel');assert.equal(distributionMode(settings,'q'),'sequential');assert.deepEqual(distributionPriority(study,{id:'p'},settings),order);saveDistributionPriority(store,study,'p',order);assert.equal(distributionMode(loadDistributionSettings(store),'p'),'parallel');assert.deepEqual(study,snapshot);assert.equal(store.getItem('pace.study-plans.v1'),'original');assert.equal(store.getItem('pace.certifications.v1'),'goals');
});
test('선택한 분배 방식을 계산 콜백에 전달하고 알 수 없는 방식은 계산을 실행하지 않는다',()=>{
 let calls=0;const calculate=mode=>{calls++;return {mode};};assert.deepEqual(previewForDistributionMode('parallel',calculate),{mode:'parallel'});assert.deepEqual(previewForDistributionMode('sequential',calculate),{mode:'sequential'});assert.equal(calls,2);assert.throws(()=>previewForDistributionMode('invalid',calculate));assert.equal(calls,2);
});
test('잘못된 분배 방식은 저장 전에 차단하고 기존 설정 필드를 덮어쓰지 않는다',()=>{
 const store=storage(),study=data(),order=distributionPriority(study,{id:'p'},loadDistributionSettings(store));saveDistributionPriority(store,study,'p',order,'parallel');const saved=JSON.parse(store.getItem(DISTRIBUTION_KEY));saved.certifications.p.custom='keep';store.setItem(DISTRIBUTION_KEY,JSON.stringify(saved));const before=store.getItem(DISTRIBUTION_KEY);assert.throws(()=>saveDistributionPriority(store,study,'p',order,'invalid'));assert.equal(store.getItem(DISTRIBUTION_KEY),before);saveDistributionPriority(store,study,'p',order,'sequential');assert.equal(loadDistributionSettings(store).certifications.p.custom,'keep');
});

import {examPrepSettings,examPrepDate,pruneExamPrepSettings} from '../src/distribution-settings.js';
test('시험 직전 항목 여러 개와 날짜를 자격증별 저장·복원하고 원본 기록은 유지',()=>{
 const store=storage(),study=data(),before=structuredClone(study),order=distributionPriority(study,{id:'p'},loadDistributionSettings(store));
 saveDistributionPriority(store,study,'p',order,'parallel',[{itemId:'p0',daysBefore:1},{itemId:'p1',daysBefore:3}]);saveDistributionPriority(store,study,'q',['B','A'],'sequential',[{itemId:'q1',daysBefore:2}]);
 const loaded=loadDistributionSettings(store);assert.deepEqual(examPrepSettings(study,'p',loaded),[{itemId:'p0',daysBefore:1},{itemId:'p1',daysBefore:3}]);assert.deepEqual(examPrepSettings(study,'q',loaded),[{itemId:'q1',daysBefore:2}]);assert.deepEqual(distributionPriority(study,{id:'p'},loaded),order);assert.equal(distributionMode(loaded,'p'),'parallel');assert.deepEqual(study,before);assert.equal(store.getItem('pace.study-plans.v1'),'original');assert.equal(store.getItem('pace.certifications.v1'),'goals');
 saveDistributionPriority(store,study,'p',order);assert.equal(examPrepSettings(study,'p',loadDistributionSettings(store)).length,2);
});
test('시험일 변경·연도 경계 날짜 계산과 시험일 미설정',()=>{assert.equal(examPrepDate('2026-10-25',1),'2026-10-24');assert.equal(examPrepDate('2026-10-28',3),'2026-10-25');assert.equal(examPrepDate('2027-01-01',2),'2026-12-30');assert.equal(examPrepDate('',1),null);assert.equal(examPrepDate('2026-10-25',0),null);});
test('항목 이름 변경에도 ID 연결 유지, 삭제·다른 자격증 항목은 정리하고 연결 해제 가능',()=>{
 const store=storage(),study=data(),order=distributionPriority(study,{id:'p'},loadDistributionSettings(store));saveDistributionPriority(store,study,'p',order,'parallel',[{itemId:'p0',daysBefore:1},{itemId:'p1',daysBefore:2},{itemId:'q1',daysBefore:1}]);study.catalog[0].title='변경 제목';assert.equal(examPrepSettings(study,'p',loadDistributionSettings(store)).length,2);study.catalog=study.catalog.filter(item=>item.id!=='p1');pruneExamPrepSettings(store,study);assert.deepEqual(loadDistributionSettings(store).certifications.p.examPrep,[{itemId:'p0',daysBefore:1}]);saveDistributionPriority(store,study,'p',distributionPriority(study,{id:'p'},loadDistributionSettings(store)),'parallel',[]);assert.deepEqual(examPrepSettings(study,'p',loadDistributionSettings(store)),[]);
});
test('잘못된 일수·중복 연결은 기존 저장 설정을 변경하지 않는다',()=>{const store=storage(),study=data(),order=distributionPriority(study,{id:'p'},loadDistributionSettings(store));for(const entries of [[{itemId:'p0',daysBefore:0}],[{itemId:'p0',daysBefore:1.5}],[{itemId:'p0',daysBefore:1},{itemId:'p0',daysBefore:2}]])assert.throws(()=>saveDistributionPriority(store,study,'p',order,'parallel',entries));assert.equal(store.getItem(DISTRIBUTION_KEY),null);});

import {saveExamPrepSettings} from '../src/distribution-settings.js';
test('오른쪽 패널은 시험 직전 설정만 저장하고 기존 우선순위·방식·다른 자격증을 보존',()=>{const store=storage(),study=data(),order=distributionPriority(study,{id:'p'},loadDistributionSettings(store));saveDistributionPriority(store,study,'p',order,'parallel',[{itemId:'p0',daysBefore:1}]);saveDistributionPriority(store,study,'q',['A','B'],'sequential',[]);const before=loadDistributionSettings(store),snapshot=structuredClone(study);const draft=examPrepSettings(study,'p',before).map(ref=>({...ref}));draft[0].daysBefore=3;assert.equal(examPrepSettings(study,'p',loadDistributionSettings(store))[0].daysBefore,1);saveExamPrepSettings(store,study,'p',draft);const after=loadDistributionSettings(store);assert.deepEqual(after.certifications.p.priority,before.certifications.p.priority);assert.equal(after.certifications.p.mode,'parallel');assert.deepEqual(after.certifications.q,before.certifications.q);assert.equal(examPrepSettings(study,'p',after)[0].daysBefore,3);assert.deepEqual(study,snapshot);assert.equal(store.getItem('pace.study-plans.v1'),'original');});
test('우선순위 미저장 상태의 패널 저장과 잘못된 일수는 안전하게 처리',()=>{const store=storage(),study=data();saveExamPrepSettings(store,study,'p',[{itemId:'p1',daysBefore:2}]);assert.equal(examPrepSettings(study,'p',loadDistributionSettings(store))[0].daysBefore,2);assert.deepEqual(distributionPriority(study,{id:'p'},loadDistributionSettings(store)),study.categoryOrder.p);const before=store.getItem(DISTRIBUTION_KEY);assert.throws(()=>saveExamPrepSettings(store,study,'p',[{itemId:'p1',daysBefore:0}]));assert.equal(store.getItem(DISTRIBUTION_KEY),before);});

import {distributionCountSettings} from '../src/distribution-settings.js';
test('개수 분배 기본 사용·자동 한도와 자격증별 설정 저장·복원, 기존 우선순위·방식·직전항목 보존',()=>{const store=storage(),study=data(),order=distributionPriority(study,{id:'p'},loadDistributionSettings(store));assert.deepEqual(distributionCountSettings(loadDistributionSettings(store),'p'),{enabled:true,dailyLimit:null});saveDistributionPriority(store,study,'p',order,'parallel',[{itemId:'p0',daysBefore:1}],{enabled:true,dailyLimit:4});saveDistributionPriority(store,study,'q',['B','A'],'sequential',[],{enabled:false,dailyLimit:2});let saved=loadDistributionSettings(store);assert.deepEqual(distributionCountSettings(saved,'p'),{enabled:true,dailyLimit:4});assert.deepEqual(distributionCountSettings(saved,'q'),{enabled:false,dailyLimit:2});saveDistributionPriority(store,study,'p',order);saveExamPrepSettings(store,study,'p',[{itemId:'p0',daysBefore:3}]);saved=loadDistributionSettings(store);assert.equal(distributionCountSettings(saved,'p').dailyLimit,4);assert.equal(distributionMode(saved,'p'),'parallel');assert.deepEqual(distributionPriority(study,{id:'p'},saved),order);const before=store.getItem(DISTRIBUTION_KEY);assert.throws(()=>saveDistributionPriority(store,study,'p',order,'parallel',[],{enabled:true,dailyLimit:0}));assert.equal(store.getItem(DISTRIBUTION_KEY),before);assert.equal(store.getItem('pace.study-plans.v1'),'original');});
