import test from 'node:test';import assert from 'node:assert/strict';
import {emptyStudy,lectureItems,materializeSavedStudy,migrateSavedStudy,STUDY_KEY,setLectureCompleted} from '../src/study.js';
const fixture=()=>({...emptyStudy(),records:[{id:'legacy',planId:'p',source:'user-supplied-table',date:'2040-02-03',ranges:{theory:'3.1~3.2, 4.1',programming:'8~9'},sourceStatus:'saved'}],completion:{legacy:{completed:true,basis:'existing'}},lectureCompletion:{'legacy:theory:3.2':{completed:false,updatedAt:'preserved'}},itemOverrides:{'legacy:theory:3.1':{date:'2040-02-05',custom:'preserved'}},catalog:[{id:'general',planId:'q',title:'existing',category:'book',date:'2040-02-06'}],categoryOrder:{p:['theory','programming']},custom:{preserved:true}});
test('legacy materialization preserves projection, stable IDs, raw records, completion and settings',()=>{const data=fixture(),before=structuredClone(data),items=lectureItems(data),next=materializeSavedStudy(data);assert.deepEqual(data,before);assert.deepEqual(lectureItems(next),items);assert.equal(next.records,data.records);assert.equal(next.completion,data.completion);assert.equal(next.lectureCompletion,data.lectureCompletion);assert.equal(next.itemOverrides,data.itemOverrides);assert.equal(next.categoryOrder,data.categoryOrder);assert.equal(next.custom,data.custom);assert.equal(materializeSavedStudy(next),next);assert.deepEqual(lectureItems(JSON.parse(JSON.stringify(next))),items);assert.equal(lectureItems(setLectureCompleted(next,items[0].id,false))[0].completed,false);});
test('stored normal items need no migration and fresh storage stays empty',()=>{const data={...emptyStudy(),catalog:[{id:'a',planId:'p',title:'normal'}]};assert.equal(materializeSavedStudy(data),data);const storage={getItem:()=>null,setItem:()=>{throw Error('must not write');}};assert.deepEqual(migrateSavedStudy(storage),emptyStudy());});
test('migration backs up exact raw storage before a single idempotent write',()=>{const raw=JSON.stringify(fixture()),map=new Map([[STUDY_KEY,raw],['pace.settings.test','keep']]),writes=[],storage={getItem:key=>map.get(key)??null,setItem:(key,value)=>{writes.push(key);map.set(key,value);}};migrateSavedStudy(storage,{backupConfirmed:true});assert.deepEqual(writes,['pace.before-catalog-migration.v1',STUDY_KEY]);assert.equal(map.get('pace.before-catalog-migration.v1'),raw);assert.equal(map.get('pace.settings.test'),'keep');migrateSavedStudy(storage,{backupConfirmed:true});assert.equal(writes.length,2);});
test('malformed range, conflicting backup and duplicate IDs never overwrite study data',()=>{for(const kind of ['range','backup','duplicate']){const data=fixture();if(kind==='range')data.records[0].ranges.theory='3.9~2.1';if(kind==='duplicate')data.catalog.push({...data.catalog[0]});const raw=JSON.stringify(data),map=new Map([[STUDY_KEY,raw],...(kind==='backup'?[['pace.before-catalog-migration.v1','other backup']]:[])]),storage={getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,value)};assert.throws(()=>migrateSavedStudy(storage,{backupConfirmed:true}));assert.equal(map.get(STUDY_KEY),raw);}});
test('deleted legacy items and explicit completion overrides stay unchanged',()=>{const data=fixture();data.deletedItemIds=['legacy:programming:9'];const before=lectureItems(data),next=materializeSavedStudy(data);assert.deepEqual(lectureItems(next),before);assert.equal(lectureItems(next).find(item=>item.id==='legacy:theory:3.2').completed,false);assert.deepEqual(next.deletedItemIds,data.deletedItemIds);});

test('unconfirmed legacy storage is read without any write',()=>{const data=fixture(),raw=JSON.stringify(data),storage={getItem:()=>raw,setItem:()=>{throw Error('must not write');}};assert.deepEqual(migrateSavedStudy(storage),data);});
