import {readFileSync} from 'node:fs';
import {importStudy} from './fixtures/synthetic-study.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {analyzeStudyInput,registerLectures,emptyStudy,lectureItems} from '../src/study.js';
test('명시적 과목 번호만 문자열 번호로 만들고 순서·분류·시간을 분리한다',()=>{const text='1과목. 소프트웨어 구축\n'+Array.from({length:10},(_,i)=>'강의 '+(i+1)+'\n시간 아이콘 32분').join('\n')+'\n2과목. 데이터베이스 구축\n데이터베이스 개념\n시간 아이콘 39분\n6과목. 신기술용어\nSW개발 동향\n시간 아이콘 43분\n신기술 용어\n시간 아이콘 44분';const rows=analyzeStudyInput({kind:'lecture',text,category:'사용자 분류'});assert.equal(rows[9].number,'1.10');assert.equal(rows[10].number,'2.1');assert.equal(rows[12].number,'6.2');assert.equal(rows[10].order,11);assert.equal(rows[10].subject,'2과목. 데이터베이스 구축');assert.ok(rows.every(r=>r.category==='사용자 분류'));assert.equal(rows[10].originalSeconds,2340);const saved=registerLectures(emptyStudy(),'p',rows).data;assert.equal(saved.catalog[9].number,'1.10');assert.equal(saved.catalog[10].subject,rows[10].subject);});
test('과목 없는 이론도 번호를 추측하지 않으며 과목 없는 항목은 빈 정보로 남긴다',()=>{const rows=analyzeStudyInput({kind:'lecture',text:'첫 번째 강의 35분\n두 번째 강의 42분',category:'이론'});assert.deepEqual(rows.map(r=>r.number),['1','2']);assert.ok(rows.every(r=>r.subject===''));const mixed=analyzeStudyInput({kind:'lecture',text:'도입 20분\n2과목. 데이터베이스\n개념 30분',category:'자유 분류'});assert.equal(mixed[0].subject,'');assert.equal(mixed[1].number,'2.1');});
test('새 번호 등록은 기존 108강 ID 배정 완료와 기존 번호를 변경하지 않는다',()=>{const {data}=importStudy(emptyStudy(),[{id:'p',name:'정보처리기사 실기',goals:[]}]);data.catalog=[{id:'old',planId:'p',category:'theory',title:'기존 제목',number:'기존 번호',order:1,type:'lecture'}];data.lectureCompletion={old:{completed:true}};const before=structuredClone(data),items=lectureItems(data);const rows=analyzeStudyInput({kind:'lecture',text:'1과목. 새 과목\n새 강의 32분',category:'theory'});const next=registerLectures(data,'p',rows).data;assert.deepEqual(data,before);assert.deepEqual(lectureItems(next).slice(0,109),items);assert.deepEqual(next.records,data.records);assert.deepEqual(next.lectureCompletion,data.lectureCompletion);assert.equal(next.catalog[0].number,'기존 번호');});

test('synthetic lecture site fixture preserves noisy metadata parsing',()=>{const text=readFileSync(new URL('./fixtures/lecture-site.txt',import.meta.url),'utf8');const rows=analyzeStudyInput({kind:'lecture',text,category:'가상 분류'});assert.equal(rows.length,9);assert.deepEqual(rows.map(row=>row.number),['1.1','1.2','1.3','2.1','2.2','2.3','3.1','3.2','3.3']);assert.equal(rows[0].title,'가상 실습 1-1');assert.equal(rows[0].originalSeconds,14*60);assert.ok(rows.every(row=>row.category==='가상 분류'));});
