import {validateExamPrep,examPrepDate,validateCountSettings} from './distribution-settings.js';
import {lectureItems} from './study.js';
import {resolveScopedAvailability,validDate} from './availability.js';
import {resolvedMilestoneCategories} from './certifications.js';
import {dateKey,daysBetween} from './calendar.js';
const EPS=1e-8;
// Pure preview: neither storage nor schedule mutations are available to this function.
export function calculateDistribution({data,plan,availability,priority=[],today=new Date(),speed=1,minutesFor,mode='sequential',examPrep=[],countSettings={enabled:true,dailyLimit:null}}){
 if(!['sequential','parallel'].includes(mode))throw Error('분배 방식을 확인해 주세요.');
 if(!plan?.id||!validDate(plan.examDate||''))throw Error('자격증의 시험일을 먼저 설정해 주세요.');
 if(!Number.isFinite(today.getTime())||typeof minutesFor!=='function'||!Number.isFinite(speed)||speed<=0)throw Error('분배 계산 설정을 확인해 주세요.');
 const first=dateKey(today),items=lectureItems(data).filter(item=>item.planId===plan.id),pending=items.filter(item=>!item.completed),completed=items.filter(item=>item.completed);
 const missing=pending.filter(item=>minutesFor(item,speed)==null),timed=pending.filter(item=>minutesFor(item,speed)!=null),categories=[...new Set([...priority,...items.map(item=>item.category)])];
 const count=validateCountSettings(countSettings),countBased=count.enabled&&missing.length>0,pool=countBased?pending:timed;
 const eligible=[];if(countBased)for(const date=new Date(today.getFullYear(),today.getMonth(),today.getDate());dateKey(date)<plan.examDate;date.setDate(date.getDate()+1)){const rule=resolveScopedAvailability(date,availability,plan.id),key=dateKey(date);if(!rule.rest&&rule.minutes>0&&!completed.some(item=>item.date===key&&minutesFor(item,speed)==null))eligible.push(key);}
 const goals=(plan.goals||[]).filter(goal=>goal.milestone?.enabled&&goal.milestone.planId===plan.id).map(goal=>({goal,categories:resolvedMilestoneCategories(data,plan.id,goal.milestone)}));
 const deadlines=new Map();for(const {goal,categories:linked} of goals)for(const category of linked){const old=deadlines.get(category);if(!old||goal.date<old)deadlines.set(category,goal.date);}
 const prep=validateExamPrep(data,plan.id,examPrep),prepIds=new Set(prep.map(ref=>ref.itemId)),prepFailures=new Map();
 for(const ref of prep){const item=pool.find(item=>item.id===ref.itemId),date=examPrepDate(plan.examDate,ref.daysBefore);if(item&&(date<first||date>=plan.examDate))prepFailures.set(item.id,'지정 날짜가 오늘부터 시험 전날까지의 기간 밖입니다.');}
 // Only the head of a category queue can be scheduled, so lectures cannot leapfrog.
 const queues=categories.map((category,rank)=>({category,rank,deadline:deadlines.get(category)||plan.examDate,items:pool.filter(item=>!prepIds.has(item.id)).map((item,index)=>({item,index})).filter(entry=>entry.item.category===category).sort((a,b)=>{const x=Number.isFinite(a.item.order)?a.item.order:a.index,y=Number.isFinite(b.item.order)?b.item.order:b.index;return x-y||a.index-b.index;}).map(entry=>entry.item)}));
 // For sequential mixed learning, leave enough study dates for whole timed items.
 // This forecast changes only the count quota; it never schedules or invents item times.
 const countStudyDays=(selectedQueues,futureDates)=>{if(mode!=='sequential')return futureDates.length;const remainingTimes=selectedQueues.flatMap(queue=>queue.items).map(item=>minutesFor(item,speed)).filter(minutes=>minutes!=null);let index=0,timedDays=0;for(const key of futureDates){const rule=resolveScopedAvailability(new Date(key+'T00:00:00'),availability,plan.id),reserved=completed.filter(item=>item.date===key).reduce((sum,item)=>sum+(minutesFor(item,speed)??0),0),designated=prep.filter(ref=>examPrepDate(plan.examDate,ref.daysBefore)===key).map(ref=>timed.find(item=>item.id===ref.itemId)).filter(Boolean).reduce((sum,item)=>sum+minutesFor(item,speed),0);let free=Math.max(0,rule.minutes-reserved-designated),used=false;while(index<remainingTimes.length&&remainingTimes[index]<=free+EPS){free-=remainingTimes[index++];used=true;}if(used)timedDays++;if(index===remainingTimes.length)break;}if(index<remainingTimes.length)timedDays=futureDates.length;return Math.max(1,futureDates.length-timedDays);};
 const assignments=[],days=[],warnings=[];let capacityTotal=0,active=[];
 for(const date=new Date(today.getFullYear(),today.getMonth(),today.getDate());dateKey(date)<plan.examDate;date.setDate(date.getDate()+1)){
  const key=dateKey(date),rule=resolveScopedAvailability(date,availability,plan.id),fixed=completed.filter(item=>item.date===key),unknownFixed=fixed.filter(item=>minutesFor(item,speed)==null),reserved=fixed.reduce((sum,item)=>sum+(minutesFor(item,speed)??0),0);
  const day={date:key,capacity:rule.minutes,reserved,used:reserved,items:[],completedIds:fixed.map(item=>item.id),unknownCompleted:unknownFixed.length,blocked:rule.rest||rule.minutes===null||unknownFixed.length>0};days.push(day);
  if(unknownFixed.length)warnings.push({date:key,reason:'완료된 항목의 시간이 미설정되어 해당 날짜의 남은 용량을 확정할 수 없습니다.'});
  if(rule.minutes===null&&rule.source!=='outside-period')warnings.push({date:key,reason:'학습 가능 시간이 미설정되어 이 날짜에는 배치하지 않았습니다.'});
  if(rule.minutes!==null&&reserved>rule.minutes+EPS)warnings.push({date:key,reason:'기존 완료 항목의 시간이 학습 가능 시간을 초과합니다. 완료 기록을 유지하고 새 항목은 배치하지 않았습니다.'});
  const designated=prep.filter(ref=>examPrepDate(plan.examDate,ref.daysBefore)===key).map(ref=>pool.find(item=>item.id===ref.itemId)).filter(Boolean),fixedCategories=new Set(fixed.map(item=>item.category));
  let countUsed=0,countLimit=count.dailyLimit;if(countBased&&countLimit==null){const futureDates=eligible.filter(value=>value>=key),remainingDays=futureDates.length,total=queues.reduce((sum,queue)=>sum+queue.items.filter(item=>minutesFor(item,speed)==null).length,0);countLimit=remainingDays?Math.ceil(total/countStudyDays(queues,futureDates)):0;for(const queue of queues){if(queue.deadline>=plan.examDate)continue;const dueDates=eligible.filter(value=>value>=key&&value<=queue.deadline),dueQueues=queues.filter(other=>mode==='sequential'?other.rank<=queue.rank:other.deadline<=queue.deadline),due=dueQueues.reduce((sum,other)=>sum+other.items.filter(item=>minutesFor(item,speed)==null).length,0);if(dueDates.length)countLimit=Math.max(countLimit,Math.ceil(due/countStudyDays(dueQueues,dueDates)));}countLimit=Math.max(countLimit,designated.filter(item=>minutesFor(item,speed)==null).length);}
  if(mode==='parallel'&&new Set([...fixedCategories,...designated.map(item=>item.category)]).size>2)warnings.push({date:key,reason:'시험 직전 지정 항목과 기존 완료 항목이 하루 최대 2개 분류 제한과 충돌합니다. 초과 분류의 지정 항목은 미배치로 남깁니다.'});
  for(const item of designated){const minutes=minutesFor(item,speed);let reason=day.blocked||rule.minutes<=0?'지정일이 쉬는 날이거나 학습 가능 시간을 확인할 수 없습니다.':mode==='parallel'&&!fixedCategories.has(item.category)&&fixedCategories.size>=2?'지정일의 하루 최대 2개 분류 제한 때문에 배치할 수 없습니다.':minutes==null&&countUsed>=countLimit?'지정일의 개수 기준 일일 한도를 초과합니다.':minutes!=null&&minutes>rule.minutes-day.used+EPS?'지정일의 남은 학습 가능 시간이 부족합니다.':null;if(reason){prepFailures.set(item.id,reason);continue;}const assignment={itemId:item.id,date:key,minutes,examPrep:true,...(minutes==null?{basis:'count'}:{})};assignments.push(assignment);day.items.push(assignment);if(minutes==null)countUsed++;else day.used=Math.min(rule.minutes,day.used+minutes);fixedCategories.add(item.category);}
  if(day.blocked)continue;
  capacityTotal+=Math.max(0,rule.minutes-reserved);
  if(countBased){
   if(rule.minutes<=0)continue;
   const dayCategories=new Set(fixedCategories);if(mode==='parallel'&&dayCategories.size>2)continue;
   const hasBasis=(queue,basis)=>queue.items.some(item=>(minutesFor(item,speed)==null?'count':'time')===basis);
   // Parallel learning shares up to two category slots across time/count work. Sequential uses one category queue.
   if(mode==='parallel'){active=active.filter(queue=>queue.items.length);for(const basis of ['count','time']){if(active.length>=2)break;if(!active.some(queue=>hasBasis(queue,basis))){const next=queues.find(queue=>queue.items.length&&!active.includes(queue)&&hasBasis(queue,basis));if(next)active.push(next);}}for(const queue of queues)if(active.length<2&&queue.items.length&&!active.includes(queue))active.push(queue);}
   const spent=new Map(),totals=new Map();for(const queue of queues){spent.set(queue,{minutes:0,count:0});totals.set(queue,{minutes:queue.items.reduce((sum,item)=>sum+(minutesFor(item,speed)??0),0),count:queue.items.filter(item=>minutesFor(item,speed)==null).length,days:Math.max(1,eligible.filter(value=>value>=key&&value<=queue.deadline).length)});}
   const fits=queue=>{if(!queue.items.length)return false;const minutes=minutesFor(queue.items[0],speed);return (minutes==null?countUsed<countLimit:minutes<=rule.minutes-day.used+EPS)&&(mode!=='parallel'||dayCategories.has(queue.category)||dayCategories.size<2);};
   while(true){let candidates;if(mode==='sequential'){const firstQueue=queues.find(queue=>queue.items.length);candidates=firstQueue&&fits(firstQueue)?[firstQueue]:[];}else candidates=active.filter(fits);if(!candidates.length)break;
    if(mode==='parallel')candidates.sort((a,b)=>{const x=spent.get(a),y=spent.get(b),started=Number(x.minutes+x.count>0)-Number(y.minutes+y.count>0);if(started)return started;const score=queue=>{const used=spent.get(queue),total=totals.get(queue),minutes=minutesFor(queue.items[0],speed);return (minutes==null?(used.count+.5)/Math.max(1,total.count):(used.minutes+minutes/2)/Math.max(EPS,total.minutes))*total.days;};return score(a)-score(b)||a.rank-b.rank;});
    const queue=candidates[0],item=queue.items.shift(),minutes=minutesFor(item,speed),assignment={itemId:item.id,date:key,minutes,...(minutes==null?{basis:'count'}:{})};assignments.push(assignment);day.items.push(assignment);if(minutes==null){countUsed++;spent.get(queue).count++;}else{day.used=Math.min(rule.minutes,day.used+minutes);spent.get(queue).minutes+=minutes;}dayCategories.add(queue.category);
   }
  }else if(mode==='parallel'){
   const dayCategories=new Set(fixedCategories);if(dayCategories.size>2){warnings.push({date:key,reason:'기존 완료 항목이 이미 세 분류 이상입니다. 기록을 유지하고 새 항목은 배치하지 않았습니다.'});continue;}
   active=active.filter(queue=>queue.items.length);for(const queue of queues)if(active.length<2&&queue.items.length&&!active.includes(queue))active.push(queue);
   const weights=new Map(),spent=new Map();
   for(const queue of active){const total=queue.items.reduce((sum,item)=>sum+minutesFor(item,speed),0);let opportunities=0;const deadline=queue.deadline<plan.examDate?queue.deadline:plan.examDate;for(const future=new Date(date);dateKey(future)<=deadline&&dateKey(future)<plan.examDate;future.setDate(future.getDate()+1)){const capacity=resolveScopedAvailability(future,availability,plan.id);if(!capacity.rest&&capacity.minutes>0)opportunities++;}weights.set(queue,total/Math.max(1,opportunities));spent.set(queue,0);}
   while(true){const free=rule.minutes-day.used,candidates=active.filter(queue=>queue.items.length&&minutesFor(queue.items[0],speed)<=free+EPS&&(dayCategories.has(queue.category)||dayCategories.size<2));if(!candidates.length)break;
    // If both heads fit, give each active category a start before weighted allocation.
    const bothFit=candidates.length===2&&candidates.reduce((sum,queue)=>sum+minutesFor(queue.items[0],speed),0)<=free+EPS;
    candidates.sort((a,b)=>{if(bothFit&&(!spent.get(a)||!spent.get(b))){const started=Number(spent.get(a)>0)-Number(spent.get(b)>0);if(started)return started;}const scoreA=(spent.get(a)+minutesFor(a.items[0],speed)/2)/weights.get(a),scoreB=(spent.get(b)+minutesFor(b.items[0],speed)/2)/weights.get(b);return scoreA-scoreB||a.rank-b.rank;});
    const candidate=candidates[0],item=candidate.items.shift(),minutes=minutesFor(item,speed),assignment={itemId:item.id,date:key,minutes};assignments.push(assignment);day.items.push(assignment);day.used=Math.min(rule.minutes,day.used+minutes);spent.set(candidate,spent.get(candidate)+minutes);dayCategories.add(candidate.category);
   }
  }else{
  while(true){const candidate=queues.filter(queue=>queue.items.length&&minutesFor(queue.items[0],speed)<=rule.minutes-day.used+EPS).sort((a,b)=>a.deadline.localeCompare(b.deadline)||a.rank-b.rank)[0];if(!candidate)break;const item=candidate.items.shift(),minutes=minutesFor(item,speed),assignment={itemId:item.id,date:key,minutes};assignments.push(assignment);day.items.push(assignment);day.used=Math.min(rule.minutes,day.used+minutes);}
  }
 }
 const assignedIds=new Set(assignments.map(entry=>entry.itemId)),remaining=timed.filter(item=>!assignedIds.has(item.id)).concat(countBased?missing.filter(item=>prepIds.has(item.id)&&!assignedIds.has(item.id)):[]),maxDayCapacity=days.filter(day=>!day.blocked).reduce((max,day)=>Math.max(max,(day.capacity??0)-day.reserved),0);
 const mixedTimedReason=item=>{const minutes=minutesFor(item,speed),openDays=days.filter(day=>!day.blocked&&day.capacity>0),free=openDays.reduce((sum,day)=>sum+Math.max(0,day.capacity-day.used),0);if(free+EPS<minutes)return '시험 전까지 남은 시간 기반 학습 가능 시간이 부족합니다.';const fitting=openDays.filter(day=>day.capacity-day.used+EPS>=minutes);if(!fitting.length)return '총 남은 시간은 있지만 하루의 남은 시간에 항목 전체가 들어가지 않습니다.';if(mode==='parallel'&&!fitting.some(day=>{const linked=[...day.items.map(entry=>items.find(item=>item.id===entry.itemId)?.category),...day.completedIds.map(id=>items.find(item=>item.id===id)?.category)];const categories=new Set(linked);return categories.has(item.category)||categories.size<2;}))return '시간은 남지만 하루 최대 2개 분류 제한으로 배치할 수 없습니다.';return '같은 분류의 선행 항목 또는 분류 우선순위 때문에 배치할 수 없습니다.';};
 const unplaced=remaining.map(item=>({itemId:item.id,minutes:minutesFor(item,speed),...(prepIds.has(item.id)?{type:'exam-prep'}:{}),reason:prepIds.has(item.id)?prepFailures.get(item.id)||'지정일에 배치할 수 없습니다.':plan.examDate<=first?'시험 전의 학습 기간이 없습니다.':!availability.certifications[plan.id]?'학습 가능 시간이 미설정되었습니다.':minutesFor(item,speed)>maxDayCapacity+EPS?'항목 시간이 하루의 남은 용량보다 커서 분할 없이 배치할 수 없습니다.':countBased?mixedTimedReason(item):'시험 전까지 남은 용량 부족 또는 분류 내 항목 순서 때문에 배치할 수 없습니다.'}));
 const schedule=new Map(assignments.map(entry=>[entry.itemId,entry.date]));
 const milestones=goals.map(({goal,categories:linked})=>{
  const targets=items.filter(item=>linked.includes(item.category)),unfinished=targets.filter(item=>!item.completed),missingCount=countBased?0:unfinished.filter(item=>minutesFor(item,speed)==null).length,unplacedCount=unfinished.filter(item=>(countBased||minutesFor(item,speed)!=null)&&!schedule.has(item.id)).length;
  const onTime=targets.filter(item=>item.completed||schedule.has(item.id)&&schedule.get(item.id)<=goal.date).length;
  const dates=unfinished.map(item=>schedule.get(item.id)).filter(Boolean).sort(),expectedDate=missingCount||unplacedCount||!linked.length?null:dates.at(-1)||targets.filter(item=>item.completed&&item.date&&item.date<=first).map(item=>item.date).sort().at(-1)||first;
  const status=!linked.length?'unlinked':missingCount?'unknown':unplacedCount?'impossible':onTime===targets.length?'met':expectedDate<=goal.date?'met':'late';
  const overlap=linked.filter(category=>goals.filter(entry=>entry.categories.includes(category)).length>1);
  return {id:goal.id,title:goal.title,date:goal.date,categories:linked,total:targets.length,onTime,remaining:targets.length-onTime,missing:missingCount,unplaced:unplacedCount,expectedDate,status,delayDays:expectedDate&&expectedDate>goal.date?daysBetween(new Date(goal.date+'T00:00:00'),new Date(expectedDate+'T00:00:00')):0,overlap};
 });
 const unassignedMissing=missing.filter(item=>!assignedIds.has(item.id)&&!(countBased&&prepIds.has(item.id)));
 const missingCounts=categories.map(category=>({category,count:unassignedMissing.filter(item=>item.category===category).length})).filter(group=>group.count);
 return {planId:plan.id,startDate:first,examDate:plan.examDate,assignments,days:days.filter(day=>day.items.length||day.completedIds.length),warnings,missing:unassignedMissing.map(item=>({itemId:item.id,...(countBased?{reason:eligible.length?'개수 기준 일일 한도 또는 분류 순서·분류 제한으로 시험 전까지 배치하지 못했습니다.':'시험 전 학습 가능한 날짜가 없습니다.'}:{})})),missingCounts,unplaced,milestones,summary:{assigned:assignments.length,assignedMinutes:Math.ceil(assignments.reduce((sum,item)=>sum+item.minutes,0)),unplaced:unplaced.length,unplacedMinutes:Math.ceil(unplaced.reduce((sum,item)=>sum+item.minutes,0)),missing:unassignedMissing.length,...(countBased?{countAssigned:assignments.filter(item=>item.basis==='count').length,countPending:missing.length,countLimit:count.dailyLimit,eligibleDays:eligible.length}:{}),remainingMinutes:Math.ceil(timed.reduce((sum,item)=>sum+minutesFor(item,speed),0)),capacityMinutes:Math.floor(capacityTotal),expectedDate:assignments.at(-1)?.date||null}};
}
